# Generated by Django 5.2.7 on 2025-10-23 23:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('token', models.CharField(max_length=128, unique=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
