# Generated by Django 5.2.7 on 2025-10-24 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='symptom',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='symptom',
            name='severity',
        ),
        migrations.RemoveField(
            model_name='symptom',
            name='symptom_text',
        ),
        migrations.AddField(
            model_name='symptom',
            name='symptom_type',
            field=models.CharField(choices=[('fever', 'Fever'), ('headache', 'Headache'), ('fatigue', 'Fatigue'), ('nausea', 'Nausea'), ('cough', 'Cough'), ('chest_pain', 'Chest Pain'), ('dizziness', 'Dizziness'), ('shortness_of_breath', 'Shortness of Breath')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ToolTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tooltips', to='measurements.patientprofile')),
                ('symptom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tooltips', to='measurements.symptom')),
            ],
        ),
    ]
