# Generated by Django 5.2.7 on 2025-11-05 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0003_rename_timestamp_symptom_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='bleeding_intensity',
            field=models.CharField(blank=True, choices=[('light', 'Light'), ('moderate', 'Moderate'), ('heavy', 'Heavy')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='diastolic_bp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='menstrual_pain',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='systolic_bp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='has_fibroid_history',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='last_menstrual_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='symptom',
            name='severity',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='symptom',
            name='symptom_type',
            field=models.CharField(choices=[('fever', 'Fever'), ('headache', 'Headache'), ('fatigue', 'Fatigue'), ('heavy_bleeding', 'Heavy Menstrual Bleeding'), ('pelvic_pain', 'Pelvic Pain'), ('frequent_urination', 'Frequent Urination'), ('bloating', 'Abdominal Bloating'), ('anemia_symptoms', 'Anemia Symptoms'), ('dizziness', 'Dizziness'), ('irregular_periods', 'Irregular Periods'), ('chest_pain', 'Chest Pain'), ('vision_changes', 'Vision Changes')], max_length=50),
        ),
        migrations.CreateModel(
            name='MenstrualCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('cycle_length', models.IntegerField(blank=True, null=True)),
                ('flow_intensity', models.CharField(choices=[('light', 'Light'), ('moderate', 'Moderate'), ('heavy', 'Heavy')], max_length=10)),
                ('pain_level', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')])),
                ('notes', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menstrual_cycles', to='measurements.patientprofile')),
            ],
        ),
    ]
